# Generated by Django 3.2.4 on 2021-07-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.TextField(max_length=2000)),
                ('biography', models.TextField(max_length=2000)),
                ('legacy', models.TextField(max_length=2000)),
                ('quotes', models.TextField(max_length=2000)),
            ],
        ),
    ]
