# Generated by Django 3.2.4 on 2021-07-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_quotes_queero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(choices=[('None', 'Community Affiliation'), ('L', 'Lesbian'), ('G', 'Gay'), ('B', 'Bisexual'), ('T', 'Transgender'), ('Q', 'Queer')], default='None', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='queero',
            name='communities',
            field=models.ManyToManyField(to='main_app.Community'),
        ),
    ]
